const express = require('express');
const authRoutes = require('./authRoutes');
const productRoutes = require('./productRoutes');
const profitRoutes = require('./profitRoutes');
const aiRoutes = require('./aiRoutes');
const stripeRoutes = require('./stripeRoutes');
const paddleRoutes = require('./paddleRoutes');
const adminRoutes = require('./adminRoutes');
const researchRoutes = require('./researchRoutes');
const launchRoutes = require('./launchRoutes');
const supplierRoutes = require('./supplierRoutes');
const productRequestRoutes = require('./productRequestRoutes');
const uploadRoutes = require('./uploadRoutes');
const sellerRoutes = require('./sellerRoutes');
const marketRoutes = require('./marketRoutes');
const publicRoutes = require('./publicRoutes');
const feedbackRoutes = require('./feedbackRoutes');
const payoutRoutes = require('./payoutRoutes');
const reviewRoutes = require('./reviewRoutes');

const router = express.Router();

router.use('/auth', authRoutes);
router.use('/products', productRoutes);
router.use('/profit', profitRoutes);
router.use('/ai', aiRoutes);
router.use('/stripe', stripeRoutes);
router.use('/paddle', paddleRoutes);
router.use('/admin', adminRoutes);
router.use('/research', researchRoutes);
router.use('/launch', launchRoutes);
router.use('/suppliers', supplierRoutes);
router.use('/requests', productRequestRoutes);
router.use('/upload', uploadRoutes);
router.use('/seller', sellerRoutes);
router.use('/marketplace', marketRoutes);
router.use('/public', publicRoutes);
router.use('/feedback', feedbackRoutes);
router.use('/payouts', payoutRoutes);
router.use('/reviews', reviewRoutes);

module.exports = router;
